# Generated by Django 2.2.5 on 2019-10-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=1)),
                ('descr', models.CharField(max_length=200)),
                ('date', models.IntegerField(max_length=45)),
            ],
        ),
    ]
